package com.mgr.bg.Controller;

import com.mgr.bg.Model.CsvEntity;
import com.mgr.bg.Repository.CsvRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * Created by Bartosz on 11/24/2018.
 */

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private CsvRepository csvRepository;
    //localhost:8080/demo/add?date=01-01-2019&Pmax=20

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser (@RequestParam String date, @RequestParam int Pmax) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        CsvEntity csvEntity = new CsvEntity();
        csvEntity.setDate(date);
        csvEntity.setPmax(Pmax);
        csvRepository.save(csvEntity);

        return "Saved : " + csvRepository.findById(csvEntity.getId()) ;
    }

    //localhost:8080/demo/all
    @GetMapping(path="/all")
    public @ResponseBody Iterable<CsvEntity> getAllEntities() {
        // This returns a JSON or XML with the users
        return csvRepository.findAll();
    }
}
