package com.mgr.bg.Controller;

import com.mgr.bg.Model.CsvEntity;
import com.mgr.bg.Repository.CsvRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * Created by Bartosz on 11/24/2018.
 */

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private CsvRepository csvRepository;
    //localhost:8080/demo/add?date=01-01-2019&Pmax=20&BOO=2&BOP=4&BPO=6&BPP=19&CO=203&CP=23

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser (@RequestParam(value = "date", required = false, defaultValue = "") String date,
                       @RequestParam(value = "Pmax", required = false, defaultValue = "0") int Pmax,
                       @RequestParam(value = "BOO", required = false, defaultValue = "0") int  BOO,
                       @RequestParam(value = "BOP", required = false, defaultValue = "0") int BOP,
                       @RequestParam(value = "BPO", required = false, defaultValue = "0")int BPO,
                       @RequestParam(value = "BPP", required = false, defaultValue = "0") int BPP,
                       @RequestParam(value = "CO", required = false, defaultValue = "0") int CO,
                       @RequestParam (value = "CP", required = false, defaultValue = "0")int CP){
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        CsvEntity csvEntity = new CsvEntity();
        csvEntity.setDate(date);
        csvEntity.setPmax(Pmax);
        csvEntity.setBOO(BOO);
        csvEntity.setBOP(BOP);
        csvEntity.setBPO(BPO);
        csvEntity.setBPP(BPP);
        csvEntity.setCO(CO);
        csvEntity.setCP(CP);
        csvRepository.save(csvEntity);

        return "Saved : " + csvRepository.findById(csvEntity.getId()) ;
    }

    //localhost:8080/demo/all
    @GetMapping(path="/all")
    public @ResponseBody Iterable<CsvEntity> getAllEntities() {
        // This returns a JSON or XML with the users
        return csvRepository.findAll();
    }
}
